name: Al_Zab_township_guide
description: A new Flutter project.
publish_to: none
version: 1.0.1+2
environment:
  sdk: '3.10.8'
  flutter: '3.38.9'

dependencies:
  flutter: 
    sdk: flutter
  cupertino_icons: 

  firebase_core:
  firebase_auth:
  email_otp: 
  cloud_firestore:
  recaptcha_enterprise_flutter: 
  provider:
  url_launcher:
  shared_preferences:
  flutter_secure_storage: ^9.0.0
  flutter_localizations:
    sdk: flutter
  firebase_database:
  intl: 
  # tutorial_coach_mark: 
  appwrite: 
    git: https://github.com/appwrite/sdk-for-flutter.git
  firebase_remote_config: 
  share_plus: 
  package_info_plus: 
  http:
  flutter_pdfview: 
  open_filex:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/logo/
    - shorebird.yaml

flutter_intl:
  enabled: true

