name = "blood"
main = "src/index.js"
compatibility_date = "2025-12-01"

[[d1_databases]]
binding = "DB"
database_name = "alzab_db"
database_id = "172378b5-6068-4dca-8a99-1a706d29566d"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "REPLACE_WITH_KV_ID"
preview_id = "REPLACE_WITH_PREVIEW_KV_ID"

[vars]
APP_NAME = "AL-Zab Township Guide"
CONFIG_TOKEN = "REPLACE_WITH_CONFIG_TOKEN"

