name = "blood"
main = "src/index.js"
compatibility_date = "2025-12-01"

[[d1_databases]]
binding = "DB"
database_name = "alzab_db"
database_id = "172378b5-6068-4dca-8a99-1a706d29566d"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "d58bb4674d8a4bb184c38b28f22788d2"
preview_id = "16d65f3150c04e849efab14643cbe34e"

[[r2_buckets]]
binding = "BOOKS_BUCKET"
bucket_name = "books"

[vars]
APP_NAME = "AL-Zab Township Guide"

[assets]
directory = "./assets"
binding = "ASSETS"

